"""empty message

Revision ID: e7cffdc7e416
Revises: 
Create Date: 2024-09-11 17:34:51.142207

"""
from app.tenders.models import TenderStatusEnum, TenderServiceTypeEnum

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7cffdc7e416'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PUBLISHED', 'CLOSED', name='tenderstatusenum'), nullable=False),
    sa.Column('organizationId', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('creatorUsername', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['creatorUsername'], ['employee.username'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_info',
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('serviceType', sa.Enum('CONSTRUCTION', 'DELIVERY', 'MANUFACTURE', name='tenderservicetypeenum'), nullable=False),
    sa.CheckConstraint('version >= 1'),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tender_id', 'version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tender_info')
    op.drop_table('tender')
    # ### end Alembic commands ###
    sa.Enum(TenderServiceTypeEnum).drop(op.get_bind())
    sa.Enum(TenderStatusEnum).drop(op.get_bind())
