"""empty message

Revision ID: 14bf1e8badcb
Revises: 
Create Date: 2024-09-13 05:46:22.454828

"""
from app.tenders.models import TenderStatusEnum, TenderServiceTypeEnum
from app.bids.models import BidStatusEnum, BidAuthorTypeEnum

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14bf1e8badcb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_version',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('version >= 1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_version',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('serviceType', sa.Enum('CONSTRUCTION', 'DELIVERY', 'MANUFACTURE', name='tenderservicetypeenum'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('version >= 1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organizationId', sa.Uuid(), nullable=False),
    sa.Column('creatorId', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PUBLISHED', 'CLOSED', name='tenderstatusenum'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['creatorId'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['tender_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bid',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenderId', sa.Uuid(), nullable=False),
    sa.Column('authorId', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PUBLISHED', 'CANCELED', name='bidstatusenum'), nullable=False),
    sa.Column('authorType', sa.Enum('ORGANIZATION', 'USER', name='bidauthortypeenum'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['authorId'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenderId'], ['tender.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['bid_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_info',
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('tender_version_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_version_id'], ['tender_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tender_id', 'tender_version_id')
    )
    op.create_table('bid_info',
    sa.Column('bid_id', sa.Uuid(), nullable=False),
    sa.Column('bid_version_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bid.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bid_version_id'], ['bid_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bid_id', 'bid_version_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bid_info')
    op.drop_table('tender_info')
    op.drop_table('bid')
    op.drop_table('tender')
    op.drop_table('tender_version')
    op.drop_table('bid_version')
    # ### end Alembic commands ###
    sa.Enum(TenderServiceTypeEnum).drop(op.get_bind())
    sa.Enum(TenderStatusEnum).drop(op.get_bind())
    sa.Enum(BidStatusEnum).drop(op.get_bind())
    sa.Enum(BidAuthorTypeEnum).drop(op.get_bind())